theme: jekyll-theme-cayman
title: OpenGates
description: "Avoid Gatekeeping in your content creation* A reference checklist of things to help you avoid gatekeeping in your dev posts, articles, videos, talks, presentations, podcasts, sites, and in any other content."
google_analytics: G-HE9PVHK0R5
