theme: jekyll-theme-cayman
title: "OpenGates"
description: "An Anti-Gatekeeping checklist for dev content creation \n(e.g. posts, articles, videos, talks, presentations, podcasts, sites, events, etc)"
google_analytics: "G-HE9PVHK0R5"
